import "../globals.css"
import { Toaster } from "@/components/ui/sonner"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex min-h-[100vh] flex-1">
        <Toaster richColors position="top-center" />
        {children}
      </body>
    </html>
  )
}
